language: java
services:
  - postgresql
before_script:
  - psql -c "ALTER ROLE postgres PASSWORD 'foo'" -U postgres
install:
  # Cypher
  - cd cypher
  - ./get-neo4j.sh
  - ./configure-neo4j.sh
  - cd ..
  # Blazegraph
  - cd sparql
  - ./get-blazegraph.sh
  - cd ..
  # driver
  - git clone https://github.com/ldbc/ldbc_snb_driver
  - cd ldbc_snb_driver
  - git checkout dev
  - mvn install -DskipTests
  - cd ..
  # environment vars
  - export POSTFIX=_0_0.csv
script:
  # Postgres
  - chmod 755 ~
  - cd postgres/load-scripts
  - ./load.sh
  - cd ../..
  # Cypher
  - cd cypher
  - cp test-data/raw/*.csv test-data/converted
  - export NEO4J_DATA_DIR=`pwd`/test-data/converted
  - cd load-scripts
  - ./convert-csvs.sh
  - ./import-to-neo4j.sh
  - ./restart-neo4j.sh
  - cd ../..
  # SPARQL
  - cd sparql
  - java -cp blazegraph.jar com.bigdata.rdf.store.DataLoader blazegraph.properties test-data/*.ttl
  - cd ..
  # tests
  - mvn test -B
notifications:
  slack: ldbcouncil:JRXP43nDV4KRgtclmoNZJpyq
  email: false
  on_success: change
  on_failure: always
